PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sn: <https://purl.org/sn/vocab#>
PREFIX esn: <https://example.org/esn/vocab#>
PREFIX csn: <https://example.org/csn/vocab#>
PREFIX isn: <https://example.org/isn/vocab#>
PREFIX osn: <https://example.org/osn/vocab#>

CONSTRUCT {
    ?A1 a csn:Country ;
        rdfs:label ?A1_label ;
        csn:inContinent ?B1 .
    ?B1 rdfs:label ?B1_label .
    ?A2 a csn:Country ;
        rdfs:label ?A2_label ;
        csn:inContinent ?B2 .
    ?B2 rdfs:label ?B2_label .
    ?relationA a csn:Trade ;
        sn:from ?A1 ; sn:into ?A2 .
    _:ATV a sn:Volume ;
        sn:relation ?relationA ;
        sn:time ?time ;
        sn:unit ?unit ;
        sn:quantity ?aggregatedQuantity .
} WHERE {
    { SELECT ?B1 ?B1_label ?B2 ?B2_label ?A1 ?A1_label ?A2 ?A2_label ?relationA ?time ?unit (SUM(?quantity) AS ?aggregatedQuantity)
        WHERE {
            ?AC1 a sn:MultidimensionalEntity ;
                sn:dimension ?A1 , ?C1 .
            ?A1 a csn:Country ;
                csn:inContinent ?B1 .
            ?C1 a isn:Industry .
            ?AC2 a sn:MultidimensionalEntity ;
                sn:dimension ?A2 , ?C2 .
            ?A2 a csn:Country ;
                csn:inContinent ?B2 .
            ?C2 a isn:Industry .
            ?ACR a sn:Relation ;
                sn:from ?AC1 ; sn:into ?AC2 .
            ?ACRV a sn:Volume ;
                sn:relation ?ACR ;
                sn:time ?time ;
                sn:unit ?unit ;
                sn:quantity ?quantity .
            ?B1 rdfs:label ?B1_label .
            ?B2 rdfs:label ?B2_label .
	        BIND ( IRI(CONCAT(STR(?A1),ENCODE_FOR_URI(?A2_label))) AS ?relationA ) .
        } GROUP BY ?B1 ?B1_label ?B2 ?B2_label ?A1 ?A1_label ?A2 ?A2_label ?relationA ?time ?unit } }
