PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sn: <https://purl.org/sn/vocab#>
PREFIX esn: <https://example.org/esn/vocab#>
PREFIX csn: <https://example.org/csn/vocab#>
PREFIX isn: <https://example.org/isn/vocab#>
PREFIX osn: <https://example.org/osn/vocab#>

CONSTRUCT {
    ?BC1 a sn:MultidimensionalEntity ;
        sn:dimension ?B1 , ?C1 .
    ?B1 a osn:Continent ;
        rdfs:label ?B1_label .
    ?C1 a isn:Industry ;
        rdfs:label ?C1_label .
    ?BC2 a sn:MultidimensionalEntity ;
        sn:dimension ?B2 , ?C2 .
    ?B2 a osn:Continent ;
        rdfs:label ?B2_label .
    ?C2 a isn:Industry ;
        rdfs:label ?C2_label .
    ?relationBC a sn:Relation ;
        sn:from ?BC1 ; sn:into ?BC2 .
    _:BCTV a sn:Volume ;
        sn:relation ?relationBC ;
        sn:time ?time ;
        sn:unit ?unit ;
        sn:quantity ?aggregatedQuantity .
} WHERE {
    { SELECT ?C1 ?C1_label ?C2 ?C2_label ?B1 ?B1_label ?B2 ?B2_label ?BC2 ?BC1 ?relationBC ?time ?unit (SUM(?quantity) AS ?aggregatedQuantity)
        WHERE {
            ?AC1 a sn:MultidimensionalEntity ;
                sn:dimension ?A1 , ?C1 .
            ?A1 a csn:Country ;
                csn:inContinent ?B1 .
            ?C1 a isn:Industry ;
                rdfs:label ?C1_label .
            ?AC2 a sn:MultidimensionalEntity ;
                sn:dimension ?A2 , ?C2 .
            ?A2 a csn:Country ;
                csn:inContinent ?B2 .
            ?C2 a isn:Industry ;
                rdfs:label ?C2_label .
            ?ACR a sn:Relation ;
                sn:from ?AC1 ; sn:into ?AC2 .
            ?ACRV a sn:Volume ;
                sn:relation ?ACR ;
                sn:time ?time ;
                sn:unit ?unit ;
                sn:quantity ?quantity .
            ?B1 rdfs:label ?B1_label .
            ?B2 rdfs:label ?B2_label .
	        BIND ( IRI(CONCAT(STR(?B1),ENCODE_FOR_URI(?C2_label))) AS ?relationBC ) .
	        BIND ( IRI(CONCAT(STR(?B1),ENCODE_FOR_URI(?C1_label))) AS ?BC1 ) .
	        BIND ( IRI(CONCAT(STR(?B2),ENCODE_FOR_URI(?C2_label))) AS ?BC1 ) .
        } GROUP BY ?C1 ?C1_label ?C2 ?C2_label ?B1 ?B1_label ?B2 ?B2_label ?BC2 ?BC1 ?relationBC ?time ?unit } }
