PREFIX sn: <https://purl.org/supply-network/onto#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK { ?sf a sn:SupplyFlow .
    OPTIONAL { ?sf sn:abstraction ?profile . }}
GROUP BY ?sf
HAVING (COUNT(DISTINCT ?profile) != 1)
