PREFIX sn: <https://purl.org/supply-network/onto#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK {
    ?from rdfs:subPropertyOf sn:from ;
        rdfs:range ?subclass .
    ?into rdfs:subPropertyOf sn:into ;
        rdfs:range ?subclass .
    FILTER NOT EXISTS { ?subclass rdfs:subClassOf sn:Entity . }
}