PREFIX sn: <https://purl.org/supply-network/onto#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK {
    ?level a sn:AbstractionLevel ;
        sn:discriminativeProperty ?prop1 , ?prop2 .
    ?prop1 rdfs:subPropertyOf ?frominto .
    ?prop2 rdfs:subPropertyOf ?frominto .
    VALUES ?frominto { sn:from sn:into }
    FILTER NOT EXISTS { ?as rdfs:domain ?prop1 .
        ?as rdfs:range ?prop2 .
        ?as rdfs:subPropertyOf sn:abstractSubstitute . } # assuming entailment for owl:TransitiveProperty
}