PREFIX : <https://purl.org/supply-network/examples#>
PREFIX geonames: <http://www.geonames.org/ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sb: <https://purl.org/supplybench#>
PREFIX sn: <https://purl.org/supply-network/onto#>

INSERT DATA {
    sb:customer rdfs:subPropertyOf sn:into ;
        rdfs:range org:Organization.
    sb:supplier rdfs:subPropertyOf sn:from ;
        rdfs:range org:Organization .
    :registeredInCountry rdfs:subPropertyOf sn:abstractSubstitute ;
        rdfs:domain org:Organization ;
        rdfs:range :Country .
    :import rdfs:subPropertyOf sn:into ;
        rdfs:range :Country .
    :export rdfs:subPropertyOf sn:from ;
        rdfs:range :Country .
    :Country rdfs:subClassOf geonames:Feature .
    sb:organizationType rdfs:subPropertyOf sn:abstractSubstitute ;
        rdfs:domain org:Organization ;
        rdfs:range sb:OrganizationType .
    :receiver rdfs:subPropertyOf sn:into ;
        rdfs:range sb:OrganizationType .
    :provider rdfs:subPropertyOf sn:from ;
        rdfs:range sb:OrganizationType . }
