PREFIX csn: <https://paul.ti.rw.fau.de/~ju32haqi/supply-networks/abstraction-examples/csn-ontology#>
PREFIX cosn: <https://paul.ti.rw.fau.de/~ju32haqi/supply-networks/abstraction-examples/cosn-ontology#>
PREFIX esn: <https://paul.ti.rw.fau.de/~ju32haqi/supply-networks/abstraction-examples/esn-ontology#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sn: <https://purl.org/supply-network/onto#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

INSERT DATA {
  wdt:P30 rdfs:subPropertyOf sn:abstractSubstitute ;
    rdfs:domain csn:Country ;
    rdfs:range wd:Q5107 .
  esn:continent rdfs:subPropertyOf sn:abstractSubstitute ;
    rdfs:domain org:Organization ;
    rdfs:range wd:Q5107 .
  cosn:import rdfs:subPropertyOf sn:into ;
    rdfs:range wd:Q5107 .
  cosn:export rdfs:subPropertyOf sn:from ;
    rdfs:range wd:Q5107 .
}