PREFIX sn: <https://purl.org/supply-network/onto#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

ASK { ?profile a sn:AbstractionProfile ;
        sn:discriminativeProperty ?prop .
    FILTER NOT EXISTS { ?prop rdfs:subPropertyOf ?frominto .
        FILTER ( ?frominto IN ( sn:from , sn:into ) ) } }